version: '3.8'

services:
  web_server:
    build: ./web_server
    container_name: web_server
    ports:
      - "5000:5000"
    networks:
      - app_network

  ai_server:
    build: ./ai_server
    container_name: ai_server
    ports:
      - "5001:5001"
    depends_on:
      - web_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge